#!/usr/local/bin/perl

use 5.010;

use strict;
use warnings FATAL => 'all';
#use diagnostics;

use Data::Dump;
#use Carp qw();

$|=1;
################################################################################
use MooseX::Declare;

class CPAN::Mini::FindDependencies {
    use autodie;
    use Archive::Tar;
    use CPAN::Meta;
    use Parse::CPAN::Packages::Fast;

    has qw(cpan_mini           is ro isa Str required 1);
    has qw(authors_path_prefix is ro isa Str);
    has qw(packages_details    is ro isa Str);
    has qw(include_suggests    is ro isa Bool default 0);
    has qw(include_recommends  is ro isa Bool default 1);
    has qw(prefer_yaml         is ro isa Bool default 0);

    sub BUILDARGS {
        my ($class, %args) = @_;

        my $cpan = $args{cpan_mini} || '';

        $args{authors_path_prefix} ||=
          join "/", $cpan, qw(authors id); # XXX
        $args{packages_details} ||=
          join "/", $cpan, qw(modules 02packages.details.txt.gz); # XXX

        return \%args;
    }

    method prefer_json() { ! $self->prefer_yaml }

    method get_meta_name($tar) {
        my ($json, $yaml);
        for ($tar->list_files) {
            $json = $_ if m{^[^/]*/META\.json$};
            $yaml = $_ if m{^[^/]*/META\.yml$};
            return $yaml if $yaml && $self->prefer_yaml;
            return $json if $json && $self->prefer_json;
        }

        return $json || $yaml;
    }

    method get_content($tar, Str $filename) {
        my $meta_file  = $tar->get_content($filename);
        return unless $meta_file;

        my $is_json = $meta_file =~ /\.json/i;
        my $method  = join '_', 'load', ($is_json ? 'json' : 'yaml'), 'string';

        return eval { CPAN::Meta->$method($meta_file) };
    }

    method get_prereqs(Str $path_suffix) {
        state $tar = Archive::Tar->new; # XXX make attribute

        $Archive::Tar::error = '';
        $tar->read(join "/", $self->authors_path_prefix, $path_suffix); # XXX
        # $bad_archive++, next unless $tar->error; # XXX what to do if error?

        my $meta_file = $self->get_meta_name($tar);
        my $meta      = $self->get_content($tar, $meta_file);

        return $meta->effective_prereqs->as_string_hash;
    }

    method get_distpath_containing(Str $package_name) {
        state $parser = Parse::CPAN::Packages::Fast->new($self->packages_details); # XXX make attribute

        my $mod  = $parser->package($package_name);
        my $dist = $mod->distribution;
        my $path = $dist->pathname;

        return $path;
    }
};
################################################################################
my $dep_finder = CPAN::Mini::FindDependencies->new(
    cpan_mini => "/mirrors/cpan",
);

my $path_suffix = $dep_finder->get_distpath_containing("CPAN::FindDependencies");
my $prereqs     = $dep_finder->get_prereqs($path_suffix);

dd $prereqs;
